--- pyproject.toml.orig	2026-02-22 22:11:36 UTC
+++ pyproject.toml
@@ -1,5 +1,5 @@
 [build-system]
-requires=['setuptools>=80.0', 'numpy>=1.25', 'scipy>=1.12', 'cykhash>=2.0', 'Cython>=3.0', 'scikit-learn>=1.3', 'hmmlearn>=0.3.2']
+requires=['setuptools>=63.0', 'numpy>=1.25', 'scipy>=1.11.1', 'cykhash>=2.0', 'Cython>=3.0', 'scikit-learn>=1.3', 'hmmlearn>=0.3.2']
 build-backend = "setuptools.build_meta"
 
 [project]
